<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Camera link -->

    <joint name="camera_joint" type="fixed">
        <parent link="platform" />
        <child link="camera_link" />
        <origin xyz="${(-base_length/2) + (realsense_length/2)} 0 ${base_height}" rpy="0 0 ${pi}"/>
    </joint>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${realsense_length} ${realsense_width} ${realsense_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </visual>
    </link> 

    <!-- Camera link - optical -->

    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link" />
        <child link="camera_optical_link" />
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <link name="camera_optical_link"></link>

    <gazebo reference="camera_link">
        <material>Gazebo/Blue</material>

        <sensor name="camera" type="camera">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <camera>
                <horizontal_fov>1.089</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>8.0</far>
                </clip>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_optical_link</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>