<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="scale_factor" value="0.001" />
    
     <!--Base size -->
    <xacro:property name="base_length" value="0.43" />
    <xacro:property name="base_width" value="0.245" />
    <xacro:property name="base_height" value="0.018" />
    <xacro:property name="base_mass" value="1" />

    <!--Castor wheel size -->
    <xacro:property name="castor_radius" value="0.022" />
    <xacro:property name="castor_height" value="0.007" />
    <xacro:property name="castor_mass" value="0.08" />

    <!--Realsense size -->
    <xacro:property name="realsense_length" value="0.09" />
    <xacro:property name="realsense_width" value="0.025" />
    <xacro:property name="realsense_height" value="0.025" />
    <xacro:property name="realsense_mass" value="0.072" />

    <!--Jetson size -->
    <xacro:property name="jetson_length" value="0.10" />
    <xacro:property name="jetson_width" value="0.079" />
    <xacro:property name="jetson_height" value="0.029" />
    <xacro:property name="jetson_mass" value="0.28" />

    <!--Odrive size
    (TODO: set teh correct dimensions)-->
    <xacro:property name="odrive_radius" value="0.0855" />
    <xacro:property name="odrive_height" value="0.045" />
    <xacro:property name="odrive_mass" value="2.2" />

    <!--Rplidar mount size-->
    <xacro:property name="rplidar_mount_length" value="0.075" />
    <xacro:property name="rplidar_mount_width" value="0.075" />
    <xacro:property name="rplidar_mount_height" value="0.045" />
    <xacro:property name="rplidar_mount_mass" value="0.34" />

    <!--Tattu battery size -->
    <xacro:property name="battery_length" value="0.17" />
    <xacro:property name="battery_width" value="0.058" />
    <xacro:property name="battery_height" value="0.062" />
    <xacro:property name="battery_mass" value="1.974" />


    <link name="base_link">

    </link>

    <!-- Platform link -->

    <joint name="platform_joint" type="fixed">
        <parent link="base_link" />
        <child link="platform" />
        <origin xyz="0 0 ${odrive_radius}" />
    </joint>

    <link name="platform">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="${base_mass}" l="${base_length}" w="${base_width}" h="${base_height}"
            xyz="0 0 0" rpy="0 0 0" />
    </link>

    <gazebo reference="platform">
        <material>Gazebo/Black</material>
    </gazebo>


    <!-- Left wheel link -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel" />
        <origin xyz="${odrive_radius + 0.04} ${(-base_width / 2) - (odrive_height/2)} ${odrive_radius}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${odrive_radius}" length="${odrive_height}" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${odrive_radius}" length="${odrive_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="${odrive_mass}" r="${odrive_radius}" h="${odrive_height}"
            xyz="0 0 0" rpy="0 0 0" />
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Grey</material>
    </gazebo>

    <!-- Right wheel link -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel" />
        <origin xyz="${odrive_radius + 0.04} ${(base_width / 2) + (odrive_height/2)} ${odrive_radius}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${odrive_radius}" length="${odrive_height}" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${odrive_radius}" length="${odrive_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="${odrive_mass}" r="${odrive_radius}" h="${odrive_height}"
            xyz="0 0 0" rpy="0 0 0" />
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Grey</material>
    </gazebo>

    <!-- Castor Wheel link -->

    <joint name="castor_joint" type="fixed">
        <parent link="base_link" />
        <child link="castor_wheel" />
        <origin xyz="${-(2/7)*base_length + 0.01} 0 ${odrive_radius/2}" rpy="0 0 0" />
    </joint>

    <link name="castor_wheel">
        <visual>
            <geometry>
                <sphere radius="${odrive_radius/2}" />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${odrive_radius/2}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="${castor_mass}" r="${castor_radius}" h="${castor_height}"
            xyz="0 0 0" rpy="0 0 0" />
    </link>

    <gazebo reference="castor_wheel">
        <material>Gazebo/Grey</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>